title: My GitHub Pages Site
description: A site demonstrating LaTeX rendering.
theme: jekyll-theme-minimal  # Or any other theme of your choice
markdown: kramdown  # Make sure this is set to kramdown

